### ISSUE TITLE
Does not remember position on restart of Atom

### ISSUE THREAD

**Issue by orschiro** [tmunro/remember-file-positions#1]
Dear @tmunro,

Thank your for this package! I am very excited to use this to remember the cursor position across sessions. 

However, I cannot figure out how to set-up the package to make it work. 

Could you please have a look at the below screencast?

Thankfully,

Robert

[file-position-2015-10-04_11.16.33.mkv | uploaded via ZenHub](https://files.zenhub.io/5610ef1c024bad464a827ab8)

**Comment by tmunro** [comment]
That is odd! My initial guess is that it has something to do with the R Markdown representation. In fact, since you're not closing the file before quitting Atom, Atom itself is restoring the file and cursor position.

My guess would be that the cursor is actually on the correct line, but the expansion of the Markdown into styled elements messed with the scroll position. Let me look at that package and see if I can discover anything - @orschiro do you mind posting your installed packages list?

Thanks for reporting this!

**Comment by tmunro** [comment]
It looks like there's a bug in Atom that prevents me from dealing with this elegantly right now:
https://github.com/atom/atom/issues/9044

I'll post here if I find a work-around.

**Comment by orschiro** [comment]
Dear @tmunro,

Thank you! It does work now. The cursor remains at the correct position. However, the last thing that doesn't work quite well is that Atom doesn't remember the corresponding view. 

Thus, there is a mismatch between what Atom is showing initially and where the cursor is placed.

But this is only a minor drawback. As soon as I start typing, the view is moving back to the original cursor position. 

~ Robert

**Comment by tmunro** [comment]
The view doesn't scroll at all, even with the updated version? It should...

**Comment by orschiro** [comment]
Sorry for the initial confusion. It indeed does scroll! 

Thank you very much. :+1: 

~ Robert
